//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerritorEx.Api.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TerritorEx.Api.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to database..
        /// </summary>
        internal static string CouldNotConnectToSatabase {
            get {
                return ResourceManager.GetString("CouldNotConnectToSatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No territory found by id {0}..
        /// </summary>
        internal static string NoTerritoryFoundById {
            get {
                return ResourceManager.GetString("NoTerritoryFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No territory found by level id {0}..
        /// </summary>
        internal static string NoTerritoryFoundByLevelId {
            get {
                return ResourceManager.GetString("NoTerritoryFoundByLevelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No territory found by name {0}..
        /// </summary>
        internal static string NoTerritoryFoundByName {
            get {
                return ResourceManager.GetString("NoTerritoryFoundByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No territory found by parent id {0}..
        /// </summary>
        internal static string NoTerritoryFoundByParentId {
            get {
                return ResourceManager.GetString("NoTerritoryFoundByParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Territory created successfully..
        /// </summary>
        internal static string TerritoryCreatedSuccessfully {
            get {
                return ResourceManager.GetString("TerritoryCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Territory deleted successfully..
        /// </summary>
        internal static string TerritoryDeletedSuccessfully {
            get {
                return ResourceManager.GetString("TerritoryDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Territory updated successfully..
        /// </summary>
        internal static string TerritoryUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("TerritoryUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a territory registered with the id {0}..
        /// </summary>
        internal static string ThereIsAlreadyTerritoryRegisteredWithId {
            get {
                return ResourceManager.GetString("ThereIsAlreadyTerritoryRegisteredWithId", resourceCulture);
            }
        }
    }
}
