//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerritorEx.Api.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TerritorEx.Api.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Área não encontrada..
        /// </summary>
        internal static string AreaNaoEncontrada {
            get {
                return ResourceManager.GetString("AreaNaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição do nível de território é obrigatória..
        /// </summary>
        internal static string DescricaoNivelTerritorioObrigatoria {
            get {
                return ResourceManager.GetString("DescricaoNivelTerritorioObrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nível do território não encontrado..
        /// </summary>
        internal static string NivelTerritorioNaoEncontrado {
            get {
                return ResourceManager.GetString("NivelTerritorioNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situação do imóvel não encontrada..
        /// </summary>
        internal static string SituacaoImovelnaoEncontrada {
            get {
                return ResourceManager.GetString("SituacaoImovelnaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentação da API do sistema TerritorEx - Sistema de Exploração do Território Rural Brasileiro..
        /// </summary>
        internal static string SwaggerDocDocumentacaoAPITerritorEx {
            get {
                return ResourceManager.GetString("SwaggerDocDocumentacaoAPITerritorEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Território não encontrado..
        /// </summary>
        internal static string TerritorioNaoEncontrado {
            get {
                return ResourceManager.GetString("TerritorioNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de imóvel não encontrado..
        /// </summary>
        internal static string TipoImovelnaoEncontrado {
            get {
                return ResourceManager.GetString("TipoImovelnaoEncontrado", resourceCulture);
            }
        }
    }
}
