// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using TerritorEx.Api.Helpers;

#nullable disable

namespace TerritorEx.Api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220824000946_V1.00.00.01")]
    partial class V1000001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TerritorEx.Api.Entities.Levels", b =>
                {
                    b.Property<int>("LevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LevelId"), 1L, 1);

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("LevelId");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("TerritorEx.Api.Entities.Territories", b =>
                {
                    b.Property<int>("TerritoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("DECIMAL(38,18)");

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("DECIMAL(38,18)");

                    b.Property<Geometry>("Shape")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<string>("TerritoryName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<int>("TerritoryParentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("TerritoryId");

                    b.HasIndex("LevelId");

                    b.HasIndex(new[] { "TerritoryParentId" }, "IX_Territories_TerritoryParentId");

                    b.ToTable("Territories");
                });

            modelBuilder.Entity("TerritorEx.Api.Entities.Territories", b =>
                {
                    b.HasOne("TerritorEx.Api.Entities.Levels", "Levels")
                        .WithMany("Territories")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Levels");
                });

            modelBuilder.Entity("TerritorEx.Api.Entities.Levels", b =>
                {
                    b.Navigation("Territories");
                });
#pragma warning restore 612, 618
        }
    }
}
